xen/riscv: introduce sbi stuff
WIP: almost it was copy from Linux kernel or OpenSBI ( need
to be checked ).

The following function sbi_cpumask_to_hartmask() was updated:
1. because SBI calls expected to recieve physical cpu ( hart ) id.
2. hart should be initialized; otherwise the following compilation
   error occurs:
     arch/riscv/sbi.c: In function 'sbi_cpumask_to_hartmask':
     arch/riscv/sbi.c:79:13: error: 'hart' may be used uninitialized [-Werror=maybe-uninitialized]
     79 |             printk(XENLOG_ERR "SBI: invalid hart=%lu for cpu=%d\n",
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     80 |                      hart, cpu);
        |                      ~~~~~~~~~~
     arch/riscv/sbi.c:71:19: note: 'hart' was declared here
     71 |     unsigned long hart;
        |                   ^~~~
     cc1: all warnings being treated as errors

Signed-off-by: Oleksii Kurochko <oleksii.kurochko@gmail.com>