xen/riscv: add dom0 xen command line argument
Currently x86/Arm defines a Xen command line argument dom0=<list> where
there can be specified dom0 controlling sub-options.

After it was introduced for Arm (f2095a51

 "xen/common: add dom0 xen command
line argument") for Arm, RISC-V compilation start to faile with
the follwing error:
  /build/xen/common/device_tree.c:2134: undefined reference to `parse_arch_dom0_param'

Signed-off-by: Oleksii Kurochko <oleksii.kurochko@gmail.com>